### PR TITLE
Pause the transaction queue when there is not enough balance to operate

### PR DESCRIPTION
**Pull request by nicoayala**
### What does this Pull Request do?
Adds a balance check (WIB and ETH) and pauses the transaction when conditions are not met.

### Are there points in the code the reviewer needs to double check?
The check is done at the beginning of the processing of every job: If there is not enough balance to start processing another job the transaction queue will finish with the current job and it will not start with another one until the transaction queue is manually resumed.

The pausing mechanism will prevent the queue from processing new jobs but it will allow to enqueue new ones. When the queue is resumed priorities and arrival order are respected.

#### Manually resume the transaction queue
On development:
```sh
$ npm run task -- txqueue:resume
```

On production:
```sh
$ npm run task:production -- txqueue:resume
```

#### Edge cases
The fact that the tx queue will do its best to finish with the current job introduces the risk of
wasting ETH and loosing the transaction if there is not enough balance. The strategy to prevent this is to have an abundant minimum WIB, so that the transaction that is being processed can do transfers if needed (the case of `CloseDataResponse`). 

Another thing that can be done to have a more robust solution is to check balance before enqueueing. This can be implemented inside the facades that need to do transfers and can be retried without problem.

### Does this Pull Request meet the acceptance criteria?
- [x] I have read the [Contribution guidelines](https://github.com/wibsonorg/buyer-sdk/CONTRIBUTING.md).
- [x] I have read the [Code of Conduct](https://github.com/wibsonorg/buyer-sdk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by Agus** [comment]
> The strategy to prevent this is to have an abundant minimum WIB, so that the transaction that is being processed can do transfers if needed

I like this one, is just a matter of communicating and setting a convenient amount of "minimum ETH/WIB"

**Comment by nicoayala** [comment]
@Agus bull does not expose a method to check if the queue is paused, and I did not find a reliable way to do it (you can ask how many jobs are in the paused queue but the result can be 0 and the queue may be paused because it did receive any new jobs). I don't think of fetching balance from the blockchain as an issue here.

**Comment by nicoayala** [comment]
> > The strategy to prevent this is to have an abundant minimum WIB, so that the transaction that is being processed can do transfers if needed
> 
> I like this one, is just a matter of communicating and setting a convenient amount of "minimum ETH/WIB"

I also find this noisy. I think I can add balance checks on both add and close dataResponse. The increaseApproval tx does not fail if there is no balance in owner's account. What do you guys think?

**Comment by Agus** [comment]
> > > The strategy to prevent this is to have an abundant minimum WIB, so that the transaction that is being processed can do transfers if needed
> > 
> > 
> > I like this one, is just a matter of communicating and setting a convenient amount of "minimum ETH/WIB"
> 
> I also find this noisy. I think I can add balance checks on both add and close dataResponse. The increaseApproval tx does not fail if there is no balance in owner's account. What do you guys think?

Aren't those transactions already handled by `transactionQueue.js` ?? In that case I think they'll be stopped anyway, so you shouldn't need to do that check again (I guess?)

**Comment by nicoayala** [comment]
@Agus @danielfx90 updated!

**Comment by danielfx90** [comment]
@manelli review it and merge it, if you are OK

**Pull request merged**
